[package]
name = "reth-net-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Types shared across network code"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true

# ethereum
alloy-rlp.workspace = true
enr.workspace = true
secp256k1.workspace = true

# async
pin-project.workspace = true
tokio = { workspace = true, features = ["full"] }

# misc
derive_more.workspace = true
